name: 'irish_housing'
version: '1.0.0'
config-version: 2

# Project profile
profile: 'irish_housing'

# Directories
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Model configurations
models:
  irish_housing:
    # Staging models (raw data transformations)
    staging:
      +materialized: view
      +schema: staging
      +tags: ['staging']

    # Core dimension and fact tables
    marts:
      core:
        +materialized: table
        +schema: marts
        +tags: ['marts', 'core']

        # Dimension tables (full refresh)
        dim_county:
          +materialized: table
        dim_date:
          +materialized: table

        # Fact tables (incremental)
        fact_listings:
          +materialized: incremental
          +on_schema_change: sync_all_columns
          +tags: ['marts', 'fact', 'incremental']

        fact_rent_market:
          +materialized: incremental
          +on_schema_change: sync_all_columns
          +tags: ['marts', 'fact', 'incremental']

        fact_cso_rent:
          +materialized: incremental
          +on_schema_change: sync_all_columns
          +tags: ['marts', 'fact', 'incremental']

      kpis:
        +materialized: view
        +schema: analytics
        +tags: ['kpis', 'analytics']

# Seeds configuration
seeds:
  irish_housing:
    +schema: seeds

# Variables
vars:
  current_year: 2026
  lookback_months: 12
