version: 2

sources:
  - name: raw
    description: Raw data tables loaded by ETL pipeline from multiple sources
    schema: public

    tables:
      # ========================================================================
      # DAFT.IE RENTAL LISTINGS
      # ========================================================================
      - name: raw_daft_listings
        description: >
          Raw rental listings scraped from Daft.ie with complete 38-field capture.
          Updated daily via automated Playwright scraper.

        columns:
          - name: id
            description: Auto-incrementing primary key
            tests:
              - not_null
              - unique

          - name: property_id
            description: Daft property ID (unique per listing)
            tests:
              - not_null

          - name: scraped_at
            description: Timestamp when listing was scraped
            tests:
              - not_null

      # ========================================================================
      # CSO RENT INDEX (RIA02)
      # ========================================================================
      - name: raw_cso_rent
        description: >
          CSO Residential Tenancies Board Average Monthly Rent data (RIA02).
          Provides official rent statistics by county, bedrooms, and property type.
          Note: NULL values are expected for some dimension combinations.

        columns:
          - name: id
            description: Auto-incrementing primary key
            tests:
              - not_null
              - unique

          - name: year
            description: Year of data
            tests:
              - not_null

      # ========================================================================
      # CSO CONSUMER PRICE INDEX (CPA01)
      # ========================================================================
      - name: raw_cso_cpi
        description: >
          CSO Consumer Price Index data (CPA01).
          Note: NULL values are expected for some time periods/categories.

        columns:
          - name: id
            description: Auto-incrementing primary key
            tests:
              - not_null
              - unique

          - name: year
            description: Year of data
            tests:
              - not_null

      # ========================================================================
      # CSO POPULATION (PEA01)
      # ========================================================================
      - name: raw_cso_population
        description: >
          CSO Population Estimates (PEA01).
          Note: NULL values are expected for some age/sex combinations.

        columns:
          - name: id
            description: Auto-incrementing primary key
            tests:
              - not_null
              - unique

          - name: year
            description: Year of data
            tests:
              - not_null

      # ========================================================================
      # CSO INCOME (CIA01)
      # ========================================================================
      - name: raw_cso_income
        description: >
          CSO Disposable Income data by county (CIA01).
          County-level income statistics for affordability analysis.

        columns:
          - name: id
            description: Auto-incrementing primary key
            tests:
              - not_null
              - unique

          - name: year
            description: Year of data
            tests:
              - not_null

      # ========================================================================
      # PROPERTY PRICE REGISTER (Future - no active scraper)
      # ========================================================================
      - name: raw_property_sales
        description: Property Price Register sales data (table exists for future use)

      # ========================================================================
      # ECB INTEREST RATES (Future - no active scraper)
      # ========================================================================
      - name: raw_ecb_rates
        description: European Central Bank interest rate data (table exists for future use)

models:
  - name: stg_daft_listings
    description: Cleaned and standardized Daft.ie rental listings with all 38 fields
    columns:
      - name: property_id
        description: Daft property ID
        tests:
          - not_null

      - name: scraped_at
        description: Scrape timestamp
        tests:
          - not_null

  - name: stg_cso_rent
    description: CSO Rent Index data (RIA02) cleaned and standardized
    columns:
      - name: year
        tests:
          - not_null

  - name: stg_cso_cpi
    description: CSO Consumer Price Index cleaned and standardized
    columns:
      - name: year
        tests:
          - not_null

  - name: stg_cso_population
    description: CSO Population estimates cleaned and standardized
    columns:
      - name: year
        tests:
          - not_null

  - name: stg_cso_income
    description: CSO Income data by county cleaned and standardized
    columns:
      - name: year
        tests:
          - not_null
